/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class TokoOutNumber extends javax.swing.JFrame {
PilihanPaketToko Toko=new PilihanPaketToko();
    /**
     * Creates new form TokoOutNumber
     */
    public TokoOutNumber() {
        initComponents();
        nonaktif();
    }
    void bersih(){
        tNama.setText("");
        tEmail.setText("");
        cPaket.setSelectedIndex(0);
        tSpec.setText("");
        tHarga.setText("");
        rKurir.setSelected(false);
        rPick.setSelected(false);
        tBiaya.setText("");
        tTotal.setText("");
        rDitoko.setSelected(false);
        rKartu.setSelected(false);
        tMasukan.setText("");
        tStruk.setText("");
    }
    void aktif(){
        tNama.setEnabled(true);
        tNama.requestFocus();
        tEmail.setEnabled(true);
        cPaket.setEnabled(true);
        tSpec.setEnabled(true);
        tSpec.setEditable(false);
        tHarga.setEnabled(true);
        tHarga.setEditable(false);
        rKurir.setEnabled(true);
        rPick.setEnabled(true);
        tBiaya.setEnabled(true);
        tBiaya.setEditable(false);
        tTotal.setEnabled(true);
        tTotal.setEditable(false);
        rDitoko.setEnabled(true);
        rKartu.setEnabled(true);
        tMasukan.setEnabled(true);
        tStruk.setEnabled(true);
        tStruk.setEditable(false);
    }
    void nonaktif(){
        tNama.setEnabled(false);
        tEmail.setEnabled(false);
        cPaket.setEnabled(false);
        tSpec.setEnabled(false);
        tHarga.setEnabled(false);
        rKurir.setEnabled(false);
        rPick.setEnabled(false);
        tBiaya.setEnabled(false);
        tTotal.setEnabled(false);
        rDitoko.setEnabled(false);
        rKartu.setEnabled(false);
        tMasukan.setEnabled(false);
        tStruk.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cPaket = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rDitoko = new javax.swing.JRadioButton();
        rKartu = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rKurir = new javax.swing.JRadioButton();
        rPick = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bIsi = new javax.swing.JButton();
        bBayar = new javax.swing.JButton();
        bTutup = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tHarga = new javax.swing.JTextField();
        tBiaya = new javax.swing.JTextField();
        tTotal = new javax.swing.JTextField();
        tMasukan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tSpec = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tStruk = new javax.swing.JTextArea();
        bBersih = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOKO OUT NUMBER");
        jLabel1.setAlignmentY(0.0F);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA DIRI");
        jLabel2.setAlignmentY(0.0F);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("E-Mail");
        jLabel3.setAlignmentY(0.0F);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nama");
        jLabel4.setAlignmentY(0.0F);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PILIH PAKET");
        jLabel5.setAlignmentY(0.0F);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Paket");
        jLabel6.setAlignmentY(0.0F);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Harga");
        jLabel7.setAlignmentY(0.0F);

        cPaket.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        cPaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "PAKET PC 1", "PAKET PC 2", "PAKET PC 3" }));
        cPaket.setAlignmentX(0.0F);
        cPaket.setAlignmentY(0.0F);
        cPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPaketActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Spesifikasi");
        jLabel8.setAlignmentY(0.0F);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pembayaran");
        jLabel9.setAlignmentY(0.0F);

        rDitoko.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        rDitoko.setText("Bayar Ditoko");

        rKartu.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        rKartu.setText("Kartu Kredit / Debit");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Masukan");
        jLabel10.setAlignmentY(0.0F);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pengiriman");
        jLabel11.setAlignmentY(0.0F);

        rKurir.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        rKurir.setText("Menggunakan Kurir");
        rKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rKurirActionPerformed(evt);
            }
        });

        rPick.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        rPick.setText("Pick Up Di toko");
        rPick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPickActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Silahkan Pilih Proses Pengiriman Yang Di Inginkan");
        jLabel12.setAlignmentY(0.0F);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Biaya");
        jLabel13.setAlignmentY(0.0F);

        bIsi.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        bIsi.setText("Isi Data");
        bIsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIsiActionPerformed(evt);
            }
        });

        bBayar.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        bBayar.setText("Bayar");
        bBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBayarActionPerformed(evt);
            }
        });

        bTutup.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        bTutup.setText("Tutup");
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Total");
        jLabel14.setAlignmentY(0.0F);

        tEmail.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        tNama.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaActionPerformed(evt);
            }
        });

        tHarga.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        tBiaya.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        tTotal.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTotalActionPerformed(evt);
            }
        });

        tMasukan.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        tSpec.setColumns(20);
        tSpec.setFont(new java.awt.Font("Monospaced", 0, 30)); // NOI18N
        tSpec.setRows(5);
        tSpec.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(tSpec);

        tStruk.setColumns(20);
        tStruk.setFont(new java.awt.Font("Monospaced", 0, 30)); // NOI18N
        tStruk.setRows(5);
        jScrollPane2.setViewportView(tStruk);

        bBersih.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        bBersih.setText("Bersih");
        bBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBersihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(557, 557, 557)
                        .addComponent(bBersih))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(592, 592, 592)
                        .addComponent(bTutup)))
                .addContainerGap(696, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(64, 64, 64)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel13)
                        .addComponent(jLabel7)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rKurir)
                                    .addGap(47, 47, 47)
                                    .addComponent(rPick)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel9)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(29, 29, 29)
                                    .addComponent(tMasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(154, 154, 154)
                                    .addComponent(bIsi)
                                    .addGap(56, 56, 56)
                                    .addComponent(bBayar))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rDitoko)
                                    .addGap(53, 53, 53)
                                    .addComponent(rKartu))))
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cPaket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tHarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(318, 318, 318)
                            .addComponent(jLabel1))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(108, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(942, Short.MAX_VALUE)
                .addComponent(bBersih)
                .addGap(541, 541, 541)
                .addComponent(bTutup)
                .addGap(578, 578, 578))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tNama))
                    .addGap(13, 13, 13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rKurir)
                        .addComponent(rPick))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(tBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(tTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rDitoko)
                        .addComponent(rKartu))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(tMasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bIsi)
                        .addComponent(bBayar))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(626, 626, 626)))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1638, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIsiActionPerformed
        JOptionPane.showMessageDialog(this, "<html><h1 style='font-family: Calibri; font-size: 36pt;'>Isi Data Dengan Teliti");
        aktif();
        bersih();
    }//GEN-LAST:event_bIsiActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed
        int tutup;
        tutup=JOptionPane.showConfirmDialog(this, "<html><h1 style='font-family: Calibri; font-size: 36pt;'>Yakin Tutup Program ? ","Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(tutup==JOptionPane.YES_OPTION)
            dispose();
        else
            return;
    }//GEN-LAST:event_bTutupActionPerformed

    private void cPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPaketActionPerformed
        Toko.setKodePaket(cPaket.getSelectedItem().toString());
        Toko.pilih(Toko.getKodePaket());
        tSpec.setText(Toko.getSpesifikasi());
        tHarga.setText(Integer.toString(Toko.getHarga()));
    }//GEN-LAST:event_cPaketActionPerformed

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void tTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTotalActionPerformed

    private void rKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rKurirActionPerformed
        rPick.setSelected(false);
        rKartu.setSelected(true);
        rDitoko.setSelected(false);
        int Biaya;
        Biaya=150000;
        tBiaya.setText(Integer.toString(Biaya));
        tTotal.setText(Integer.toString(Toko.getHarga()+Biaya));
        jLabel10.setText("Masukan Nomor Kartu Anda");
        tMasukan.setVisible(true);
        tMasukan.requestFocus();
    }//GEN-LAST:event_rKurirActionPerformed

    private void rPickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPickActionPerformed
        rKurir.setSelected(false);
        rDitoko.setSelected(true);
        rKartu.setSelected(false);
        tBiaya.setText("Gratis");
        tTotal.setText(Integer.toString(Toko.getHarga()));
        jLabel10.setText("Pembayaran Akan Dilakukan Di Toko");
        tMasukan.setVisible(false);
    }//GEN-LAST:event_rPickActionPerformed

    private void bBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBayarActionPerformed
       String nama=(tNama.getText());
       String paket=Integer.toString(cPaket.getSelectedIndex());
       String spec=(tSpec.getText());
       String harga=(tHarga.getText());
       boolean pilihan;
       String keterangan = null;
       int biayatambah = 0;
       if(pilihan=rKurir.isSelected())
       {
           keterangan="Anda Memilih Menggunakan Kurir Untuk Pengiriman";
           biayatambah=150000;
       }
       else if(pilihan=rPick.isSelected())
       {
           keterangan="Anda Memilih Pick Up Di Toko. Mohon Ambil Pesanan Anda Ditoko";
           biayatambah=0;
       }
       boolean pilihbayar;
       String ketbayar = null;
       if(pilihbayar=rDitoko.isSelected())
       {
           ketbayar="Lakukan Pembayaran Di Toko";
       }
       else if(pilihbayar=rKartu.isSelected())
       {
           ketbayar="Anda Membayar Dengan Kartu Debit / Kredit Anda";
       }
       String total=(tTotal.getText());
       tStruk.setText("Pembayaran Berhasil"
               + "\nNama : "+nama
               + "\nPilihan Paket : "+paket
               + "\nSpefifikasi : \n"+spec
               + "\nHarga : Rp."+harga
               + "\nMetode Pengiriman : "+keterangan
               + "\nBiaya Tambahan : Rp."+biayatambah
               + "\nTotal Bayar : Rp."+total
               + "\nMetode Pembayaran : "+ketbayar
               + "\nTerima Kasih");
    }//GEN-LAST:event_bBayarActionPerformed

    private void bBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBersihActionPerformed
        bersih();
    }//GEN-LAST:event_bBersihActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoOutNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoOutNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoOutNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoOutNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoOutNumber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBayar;
    private javax.swing.JButton bBersih;
    private javax.swing.JButton bIsi;
    private javax.swing.JButton bTutup;
    private javax.swing.JComboBox<String> cPaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rDitoko;
    private javax.swing.JRadioButton rKartu;
    private javax.swing.JRadioButton rKurir;
    private javax.swing.JRadioButton rPick;
    private javax.swing.JTextField tBiaya;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tMasukan;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextArea tSpec;
    private javax.swing.JTextArea tStruk;
    private javax.swing.JTextField tTotal;
    // End of variables declaration//GEN-END:variables
}
